### PR TITLE
added simple progress status

### PR DESCRIPTION
**Pull request by poldi1405**
I've added a simpler progress status report that should be easier on the eyes for everyday use.

### CODE REVIEW

**Comment by poldi1405** [comment]
I've also made a version with a spinner but I'm not sure if this would be preferable.
[with-spinner.diff.txt](https://github.com/melbahja/got/files/5121991/with-spinner.diff.txt)

**Comment by poldi1405** [comment]
tests are failing because therer is an issue in download_test.go:194: Corrupted file

not my fault though

**Comment by poldi1405** [comment]
Just tried it and it works just fine on Windows and Linux.

The checksum of the downloaded file matches the checksum provided by http://www.ovh.net/files/sha1sum.txt

**Comment by melbahja** [comment]
The new progress looks very nice you can make it the default. and remove the old one and `simple` flag. and add build tags on  `variables_*` files like on darwin file:
```go
// +build darwin
```

**Comment by melbahja** [comment]
The `Corrupted file` test error it just because I've used `go.mod` file for testing :facepalm:, I will fix it

**Comment by poldi1405** [comment]
I used the version without the spinner. If you want to use it the patch should be easy to apply after some modification.

**Comment by melbahja** [comment]
Looks nice thank you :), I will fix the test errors before merge.

**Pull request merged**
